version: '3.9'

services:
  backend:
    build: .
    container_name: chat-rio-backend
    ports:
      - "8894:8894"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo:6
    container_name: chat-rio-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:7
    container_name: chat-rio-redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mongo_data:
